site_name: NC Flower Report
site_description: Tracking THCA flower pricing and value across North Carolina

theme:
  name: material
  palette:
    scheme: slate

nav:
  - Guide: index.md

markdown_extensions:
  - admonition
  - tables
  - toc:
      permalink: true
